from multiprocessing.connection import wait
import pyautogui as p_y
import webbrowser as w_b
import time
StartingMessage = "AttackStarted"

print(StartingMessage)

w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")
w_b.open("www.google.com")

